export const images = [
  { src: "/assets/testimoni/testi1.jpg", alt: "Pelanggan puas dengan layanan nail art" },
  { src: "/assets/testimoni/testi2.jpg", alt: "Hasil nail art yang elegan dan modern" },
  { src: "/assets/testimoni/testi3.jpg", alt: "Pelanggan menunjukkan hasil manikur" },
  { src: "/assets/testimoni/testi4.jpg", alt: "Koleksi desain nail art kreatif" },
  { src: "/assets/testimoni/testi5.jpg", alt: "Testimoni pelanggan setelah treatment" },
  { src: "/assets/testimoni/testi6.jpg", alt: "Desain kuku warna-warni populer" },
  { src: "/assets/testimoni/testi7.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi8.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi9.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi10.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi11.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi12.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi13.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi14.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi15.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi16.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi17.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi18.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi19.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi20.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi21.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi22.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi23.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi24.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi25.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi26.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi27.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi28.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi29.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi30.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi31.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi32.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi33.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi34.jpg", alt: "Hasil perawatan kuku profesional" },
];
