export const images = [
  { src: "/assets/testimoni/testi1.jpg", alt: "Pelanggan puas dengan layanan nail art" },
  { src: "/assets/testimoni/testi2.jpg", alt: "Hasil nail art yang elegan dan modern" },
  { src: "/assets/testimoni/testi3.jpg", alt: "Pelanggan menunjukkan hasil manikur" },
  { src: "/assets/testimoni/testi4.jpg", alt: "Koleksi desain nail art kreatif" },
  { src: "/assets/testimoni/testi5.jpg", alt: "Testimoni pelanggan setelah treatment" },
  { src: "/assets/testimoni/testi6.jpg", alt: "Desain kuku warna-warni populer" },
  { src: "/assets/testimoni/testi7.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi8.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi9.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi10.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi11.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi12.jpg", alt: "Hasil perawatan kuku profesional" },
  { src: "/assets/testimoni/testi13.jpg", alt: "Hasil perawatan kuku profesional" },
];
